### ISSUE TITLE
Deep sea treasure We have found that there is an error in the _is_valid_state of the environment.

### ISSUE THREAD

**Issue by Daiki04** [Farama-Foundation/MO-Gymnasium#111]
Deep sea treasure I found that there was an error in the _is_valid_state of the environment. In the MIRRORED environment, the x-coordinate is from 0 to 19, but the _is_valid_state is set so that the x-coordinate can only be from 0 to 10. If you rewrite the _is_valid_state as follows, it will work correctly.
```python
    def _is_valid_state(self, state):
        if self.map_name == "mirrored":
            if state[0] >= 0 and state[0] <= 10 and state[1] >= 0 and state[1] <= 19:
                if self._get_map_value(state) != -10:
                    return True
            return False
        else:
            if state[0] >= 0 and state[0] <= 10 and state[1] >= 0 and state[1] <= 10:
                if self._get_map_value(state) != -10:
                    return True
            return False
```

**Comment by ffelten** [comment]
Hi @Daiki04, 

Indeed, I forgot to change that function when including the mirrored version. Would you mind submitting a PR with these changes? :)

Thanks a lot,

Florian
