### ISSUE TITLE
Is the rewards of "E1" or "E2" in the step function designed incorrectly?

### ISSUE THREAD

**Issue by HONG-ZI** [Farama-Foundation/MO-Gymnasium#23]
The paper [1] said "if it steps on one of the two enemy spaces, labeled E1 and E2, with a 10% probability it will be attacked, receiving a penalty and resetting to the home space, losing all it carries." That means if the agent encounters the "E1" or "E2", at the probability of 10%, "self.current_pos" should be self.initial_pos, and the "vec_reward" should be [-1,0,0]. 

But in function Step(), 

elif cell == "E1" or cell == "E2":
            if np.random.random() < 0.1:
                vec_reward[0] = -1.0
                done = True

the "self.current_pos" and the "vec_reward[1]" and the "vec_reward[2]" are not adjusted.

[1] L. Barrett and S. Narayanan, “Learning all optimal policies with multiple criteria,” in Proceedings of the 25th international conference on Machine learning - ICML ’08, Helsinki, Finland, 2008, pp. 41–47. doi: [10.1145/1390156.1390162](https://doi.org/10.1145/1390156.1390162).

**Comment by LucasAlegre** [comment]
Hi @HONG-ZI ,

`vec_reward[1]` and `vec_reward[2]` are already 0 because of their initialization in line 147.

`self.current_pos` is reset on the `reset()` method, which should be called next because `done=True`
