### ISSUE TITLE
MORecordEpisodeWrapper should not be vectorized

### ISSUE THREAD

**Issue by ffelten** [Farama-Foundation/MO-Gymnasium#28]
When the underlying environment is not vectorized, MORecordEpisodeWrapper should not return a (1, reward_dim) shape, but a (reward_dim) shape.
+ fix test

**Comment by ChrisZonghaoLi** [comment]
Hi there, sorry but could you please specify where this class is located at? I was digging around `utils.py` and only find `MORecordEpisodeStatistics`. Are you referring to this class? Thanks.

**Comment by ffelten** [comment]
@ChrisZonghaoLi yeah, I was referring to that one. I have a PR coming up for that.
