### ISSUE TITLE
Add MO-Walker and MO-Swimmer

### ISSUE THREAD

**Issue by LucasAlegre** [Farama-Foundation/MO-Gymnasium#39]
We could easily also add MO versions of the Walker and Swimmer robots, as in: https://openreview.net/forum?id=Ki4ocDm364

**Comment by ffelten** [comment]
(!) Mujoco recently introduced breaking changes so we need to pin to `2.3.3`. From `>=2.3.4`, we might need to move to mujoco v5 which is still unclear for Walker and Hopper from what I understood from the discussions within Farama.
