### ISSUE TITLE
Add "reward_weights" to info for LinearRewardWrapper

### ISSUE THREAD

**Issue by ianleongudri** [Farama-Foundation/MO-Gymnasium#68]
There are various multitask algorithms (such as [Successor Features](https://www.deepmind.com/blog/fast-reinforcement-learning-through-the-composition-of-behaviours)) that make use of the specific reward weights for a given episode as part of their learning. I propose adding the following at line 68 of mo_gymnasium/utils.py:

`        info["reward_weights"] = self.w`

**Comment by ffelten** [comment]
Hello,

Thank you for the proposal. However, I fail to see cases where you do not already have access to the reward weights from your agent ? It seems to me that the reward weights make more sense to be stored in the agent rather than the environment?

**Comment by LucasAlegre** [comment]
Hi,

My question is: why do you need reward weights in the info dict if it can be accessed directly in the env with `env.w`?

**Comment by ffelten** [comment]
Seems valid to me then. Could you open a PR with that? :)

**Comment by LucasAlegre** [comment]
Solved at #69
