### ISSUE TITLE
[Website, feature] Group the environments by types

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/MO-Gymnasium#82]
Would it be possible for the website to group environment by their type? 

When I was look at the list of the environment, I found it difficult to see all of the mujoco environments. 
It should be possible to do, see Gymnasium's implementation of this

For the types, you will know better than me but something like `grid-based, mujoco, games, misc`

**Comment by LucasAlegre** [comment]
Thanks for the suggestion! I will work on that in PR #83

**Comment by LucasAlegre** [comment]
Completed in #83
